build: Work around broken pymarkdownlnt
pymarkdownlnt 0.9.13 fails with:

ModuleNotFoundError: No module named 'pymarkdown.general'

Thus, update tox.ini to avoid this version.